# Generated by Django 4.2 on 2026-06-01 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_cases', to=settings.AUTH_USER_MODEL, verbose_name='Отклонившие адвокаты'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('pending', 'На рассмотрении'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
